# Generated by Django 5.0.6 on 2024-06-22 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='ano_livro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='dono_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
