# Generated by Django 5.0.6 on 2024-06-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_biblioteca_ano_livro_alter_biblioteca_dono_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='categoria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
